CREATE TABLE ESPECIALIDAD (
  ID INT PRIMARY KEY,
  NOMBRE_ESPECIALIDAD VARCHAR(45),
  DESCRIPCION_ESPECIALIDAD VARCHAR(45));

CREATE TABLE PROFESIONAL_SALUD (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NOMBRE TINYTEXT ,
  TARJETA_PROFESIONAL VARCHAR(45) ,
  HASH VARCHAR(64),
  SAL VARCHAR(64) ,
  REFERENCIA_PFP VARCHAR(200),
  ESPECIALIDAD_ID INT ,

  INDEX (ESPECIALIDAD_ID) ,
  FOREIGN KEY (ESPECIALIDAD_ID)
  REFERENCES ESPECIALIDAD(ID));


CREATE TABLE ENFERMEDAD(
  ID INT  AUTO_INCREMENT ,
  NOMBRE_ENFER VARCHAR(45) ,
  DESCRIPCION_ENFER VARCHAR(45) ,
  PRIMARY KEY (ID));



CREATE TABLE PACIENTE (
  ID INT,
  HASH VARCHAR(64) ,
  SEXO ENUM('FEMENINO', 'MASCULINO', 'INTERSEXUALIDAD') ,
  SALT VARCHAR(64) ,
  NOMBRE TINYTEXT  ,
  FECHA_NACIMIENTO DATE ,
  LUGAR_NACIMIENTO VARCHAR(45) ,
  TIPO_SANGRE ENUM('O+', 'O-', 'A+', 'A-', 'B+', 'B-', 'AB+', 'AB-') ,
  EMAIL VARCHAR(45)  ,
  DIRECCION VARCHAR(45),
  TELEFONO_MOVIL INT ,
  TELEFONO_FIJO INT ,
  ESTADO_CIVIL ENUM('SOLTERO/A', 'CASADO/A', '') ,
  REFERENCIA_PFP VARCHAR(200) ,
  PRIMARY KEY (ID));



CREATE TABLE HISTORIAL_CLINICO (
  ID INT ,
  FECHA_FORM DATE ,
  PASADO_MED TEXT NULL ,
  SINTOMAS TEXT NULL ,
  HISTORIAL_FAMILIAR TEXT NULL ,
  HISTORIAL_MEDICACION TEXT NULL ,
  ALERGIAS TEXT NULL,
  RESULTADOS_LAB TEXT NULL ,
  EXAMEN_FIS TEXT NULL ,
  ENFERMEDAD_ID INT ,
  PACIENTE_ID INT,
  PROFESIONAL_SALUD_ID INT ,
  PRIMARY KEY (ID),
  INDEX  (ENFERMEDAD_ID),
  INDEX (PACIENTE_ID) ,
  INDEX (PROFESIONAL_SALUD_ID) ,
  FOREIGN KEY (ENFERMEDAD_ID)
  REFERENCES ENFERMEDAD(ID),
    FOREIGN KEY (PACIENTE_ID)
    REFERENCES PACIENTE(ID),
    FOREIGN KEY (PROFESIONAL_SALUD_ID)
    REFERENCES PROFESIONAL_SALUD (ID));


CREATE TABLE PRODUCTO(
  ID INT ,
  NOMBRE VARCHAR(45),
  DESCRIPCION TEXT,
  CATEGORIA VARCHAR(50) ,
  CANTIDAD_STOCK INT,
  CANTIDAD_MIN INT ,
  CANTIDAD_MAX INT ,
  PRIMARY KEY (ID));



CREATE TABLE TRANSACCION(
  ID INT,
  FECHA_ADQ DATETIME NULL ,
  CANTIDAD INT NULL ,
  FECHA_VEN DATETIME NULL ,
  PRODUCTO_ID INT ,
  PRIMARY KEY (ID),
  INDEX (PRODUCTO_ID) ,
    FOREIGN KEY (PRODUCTO_ID)
    REFERENCES PRODUCTO(ID));




CREATE TABLE TRANS_PROD (
  PRODUCTO_ID INT ,
  PROFESIONAL_ID INT,
  FECHA DATETIME ,
  CANTIDAD INT ,
  PRIMARY KEY (PRODUCTO_ID, PROFESIONAL_ID),
  INDEX  (PROFESIONAL_ID) ,
  INDEX  (PRODUCTO_ID) ,
 
    FOREIGN KEY (PRODUCTO_ID)
    REFERENCES PRODUCTO(ID),
    FOREIGN KEY (PROFESIONAL_ID)
    REFERENCES PROFESIONAL_SALUD(ID));




CREATE TABLE TIPO_USUARIO (
  ID INT ,
  NOMBRE VARCHAR(200) ,
  DESCRIPCION TEXT ,
  PRIMARY KEY (ID));


CREATE TABLE USUARIO (
  ID INT ,
  HASH VARCHAR(64) ,
  TIPO_USUARIO_ID INT,
  SALT VARCHAR(64) ,
  NOMBRE TINYTEXT ,
  EMAIL VARCHAR(45) ,
  DIRECCION VARCHAR(45) ,
  REFERENCIA_PFP VARCHAR(200) ,
  PRIMARY KEY (ID),
  INDEX (TIPO_USUARIO_ID) ,
  
    FOREIGN KEY (TIPO_USUARIO_ID)
    REFERENCES TIPO_USUARIO(ID));




CREATE TABLE BENEFICIARIO(
  FECHA_AF DATE ,
  PACIENTE_ID INT ,
  INDEX (PACIENTE_ID) ,

    FOREIGN KEY (PACIENTE_ID)
    REFERENCES PACIENTE(ID));



CREATE TABLE LOG(
  ID INT ,
  UBICACION TEXT ,
  USUARIO_ID INT ,
  PRIMARY KEY (ID),
  INDEX (USUARIO_ID) ,

    FOREIGN KEY (USUARIO_ID)
    REFERENCES USUARIO(ID));

CREATE TABLE CITA(
  ID INT,
  FECHA_ASIG DATETIME,
  ID_PACIENTE INT ,
  ID_MEDICO INT ,
  TIPO ENUM('AGENDADA', 'CANCELADA', 'ASISTIDA') NULL ,
  PRIMARY KEY (ID),
  FOREIGN KEY (ID_PACIENTE)
  REFERENCES PACIENTE(ID),
  FOREIGN KEY (ID_MEDICO)
  REFERENCES PROFESIONAL_SALUD(ID));




